# Generated by Django 5.0.3 on 2024-03-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bet', '0001_initial'),
        ('playable', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicebet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multichoicebetresolver',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolver', to='players.businessunit'),
        ),
        migrations.AddField(
            model_name='multichoicebetresolver',
            name='playable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolver', to='playable.multichoice'),
        ),
        migrations.AddField(
            model_name='multichoicebet',
            name='resolver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bet.multichoicebetresolver'),
        ),
    ]
